services:

  app:
    build: .
    container_name: catalog_app
    command: python src/cli.py run-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "9000:9000"
    env_file:
      - .env
    tty: true
    stdin_open: true
