services:

  app:
    image: ghcr.io/acatejr/catalog:latest
    container_name: catalog_app_dev
    command: python src/cli.py run-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
