services:

  catalogdb:
    container_name: catalogdb
    image: ankane/pgvector
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: