services:

  catalog:
    image: acatejr/catalog:latest
    build: .
    env_file:
      - .env
    volumes:
      - static:/var/www/static
      - media:/var/www/media
    stdin_open: true
    tty: true
    depends_on:
      - db
    restart: unless-stopped
    command: "uvicorn main.asgi:application --reload --host 0.0.0.0 --port 8000"

  db:
    container_name: catalogdb
    image: postgres:latest
    env_file: .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    container_name: catalog_caddy
    image: caddy:latest    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Caddy specific urls
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - type: volume
        source: media
        target: /usr/share/caddy/media
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: static
        target: /usr/share/caddy/static
        read_only: true
        volume:
          nocopy: true
    restart: unless-stopped

volumes:
  pgdata:
  static:
  media: