services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    tty: true
    stdin_open: true
