site_name: Catalog Documentation

theme:
  name: material

plugins:
    - search
    - mermaid2
    - asciinema-player

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/acatejr/catalog
repo_name: acatejr/catalog
