services:

  # catalog:
  #   container_name: catalog
  #   image: catalog
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - $PWD:/catalog
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped

  db:
    container_name: catalogdb
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - neo4j_db_data:/data
      - neo4j_db_logs:/logs
      - neo4j_db_import:/var/lib/neo4j/import
      - neo4j_db_plugins:/plugins

volumes:
  pgdata:
  neo4j_db_data:
  neo4j_db_logs:
  neo4j_db_import:
  neo4j_db_plugins:
