services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sql77!
      - POSTGRES_DATABASE=catalog_dev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
