# Generated by Django 5.0.6 on 2024-06-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_setup_domain_hierarchy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rootdomain",
            options={
                "verbose_name": "Root Domain",
                "verbose_name_plural": "Root Domain",
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="description",
            field=models.CharField(
                help_text="Domain name description (optional)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rootdomain",
            name="description",
            field=models.CharField(
                help_text="Domain name description (optional)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(
                help_text="Domain name (required)", max_length=250, unique=True
            ),
        ),
    ]
