# Generated by Django 5.0.6 on 2024-06-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_added_host_attribs_on_domain_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='format',
            field=models.CharField(choices=[('TABULAR', 'Tabular'), ('TABULAR_AND_GEOSPATIL', 'Tabular and Geospatial'), ('GEOSPATIAL', 'Geospatial'), ('N/A', 'N/A')], help_text='The data format', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='host_system_name',
            field=models.CharField(help_text='System name currently hosting the data (i.e. Redshift,  Oracle)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='host_system_type',
            field=models.CharField(help_text='System type currently hosting the data', max_length=500, null=True),
        ),
    ]
