# Generated by Django 5.0.6 on 2024-06-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_allow_host_related_fields_to_be_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('metadata_url', models.CharField(blank=True, help_text='The url used to access/retrieve the metadata.', max_length=1500, null=True, unique=True)),
                ('description', models.CharField(blank=True, help_text='The description of the metadata document.', max_length=3000, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
