# Generated by Django 5.0.6 on 2024-06-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_added_name_to_asset_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='title',
        ),
    ]
