# Generated by Django 5.0.6 on 2024-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_added_searc_term_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
