"""Tweaking Document model

Revision ID: 2668e59e7f00
Revises: 5555e336b05a
Create Date: 2024-06-06 11:50:56.765881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2668e59e7f00'
down_revision: Union[str, None] = '5555e336b05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone='TRUE'),
               nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone='TRUE'),
               nullable=False)
    op.drop_constraint('documents_metadata_url_key', 'documents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('documents_metadata_url_key', 'documents', ['metadata_url'])
    op.alter_column('documents', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone='TRUE'),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=sa.TIMESTAMP(timezone='TRUE'),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
