"""Added SearchTermLog table.

Revision ID: 575c693e89ae
Revises: 2668e59e7f00
Create Date: 2024-06-06 13:47:22.484793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "575c693e89ae"
down_revision: Union[str, None] = "2668e59e7f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=2500), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone="TRUE"),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone="TRUE"),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_terms")
    # ### end Alembic commands ###
