# Generated by Django 5.0.6 on 2024-05-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_added_source_ur_and_type_to_document_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='source_url',
            new_name='metadata_url',
        ),
    ]
