name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Ready for deploy
        run: |
          echo "This is a placeholder for deployment steps."
          ls -l

      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /ubuntu/apps/catalog
            git pull origin main
            # sudo systemctl restart catalog.service
            echo "Deployment to Test Server completed."
