name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /root/apps/catalog
          git pull origin main
        #   docker compose stop
        #   docker compose start
          echo "Deployment to Test Server completed."
